name: wise_spends
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  ionicons: ^0.2.2
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path: ^1.9.1
  path_provider: ^2.1.5
  uuid: ^4.5.1
  rxdart: ^0.28.0
  group_radio_button: ^1.3.0
  permission_handler: ^12.0.1
  external_path: ^2.2.0
  file_picker: ^10.3.3
  intl: ^0.20.2
  bloc: ^9.1.0
  meta: ^1.17.0
  settings_ui: ^2.0.2
  dropdown_textfield: ^1.2.0
  get_it: ^8.2.0

dependency_overrides:
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.29.0
  build_runner: ^2.10.1

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
