name: wise_spends
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  ionicons: ^0.1.2
  drift: ^1.0.1
  sqlite3_flutter_libs: ^0.5.12
  path: ^1.8.0
  path_provider: ^2.0.10
  uuid: ^3.0.7
  rxdart: ^0.27.7
  group_radio_button: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^1.0.2
  build_runner: ^2.2.0

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
