name: wise_spends
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  ionicons: ^0.2.1
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.12
  path: ^1.8.2
  path_provider: ^2.0.11
  uuid: ^4.2.2
  rxdart: ^0.27.7
  group_radio_button: ^1.3.0
  permission_handler: ^11.1.0
  external_path: ^1.0.3
  file_picker: ^6.1.1
  intl: ^0.19.0
  bloc: ^8.1.0
  meta: ^1.8.0
  settings_ui: ^2.0.2
  dropdown_textfield: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.4.1
  build_runner: ^2.4.7

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
