name: wise_spends
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  ionicons: ^0.2.2
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24
  path: ^1.9.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  rxdart: ^0.28.0
  group_radio_button: ^1.3.0
  permission_handler: ^11.3.1
  external_path: ^1.0.3
  file_picker: ^8.0.5
  intl: ^0.19.0
  bloc: ^8.1.4
  meta: ^1.12.0
  settings_ui: ^2.0.2
  dropdown_textfield: ^1.2.0
  get_it: ^7.7.0

dependency_overrides:
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.18.0
  build_runner: ^2.4.11

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700

  assets:
    - assets/images/facebook.png
    - assets/images/google.png
