import 'package:equatable/equatable.dart';

class AutogeneratedHomeLoggedIn {
  final List<HomeLoggedInModel> results;

  AutogeneratedHomeLoggedIn({required this.results});

  factory AutogeneratedHomeLoggedIn.fromJson(Map<String, dynamic> json) {
    var temp = <HomeLoggedInModel>[];
    if (json['results'] != null) {
      temp = <HomeLoggedInModel>[];
      json['results'].forEach((v) {
        temp.add(HomeLoggedInModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedHomeLoggedIn(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['results'] = results.map((v) => v.toJson()).toList();
    return data;
  }
}

class HomeLoggedInModel extends Equatable {
  final int id;
  final String name;

  const HomeLoggedInModel(this.id, this.name);

  @override
  List<Object> get props => [id, name];

  factory HomeLoggedInModel.fromJson(Map<String, dynamic> json) {
    return HomeLoggedInModel(json['id'] as int, json['name'] as String);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    return data;
  }
}
